name: MainGithub Actions
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  test_suie:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.6.0'
    - run: npm ci
    - name: run test
      run: npm run test:headless
    - name: Copy History
      if: always()
      run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history
    - name: Generate Report
      if: always()
      run: npm run allure:generate  # Name of the allure generate script 
    - name: Upload Results
      uses: actions/upload-artifact@v1
      if: always()
      with: 
        name: allure-results
        path: ./allure-results
    - name: Publishing Allure artifact to Github Actions
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: allure-report
        path: allure-report
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: always()
      with:
        branch: gh-pages
        folder: allure-report
        target-folder: docs
    - name: Pushes docs to another repository
      uses: cpina/github-action-push-to-another-repository@v1.3
      if: always()
      env: 
        API_TOKEN_GITHUB: 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
      with:
        source-directory: 'docs'
        destination-github-username: pokeyrover
        destination-repository-name: github_page_testing_project
        user-email: pokeyrover@gmail.com
        target-branch: gh-pages


